apiVersion: v1
kind: Secret
metadata:
  name: mongodb-user
  namespace: production
  labels:
    app: tasky
    type: frontend
type: Opaque
stringData:
  MONGODB_URI: "mongodb://${USERNAME}:${PASSWORD}@${MONGODB_PRIVATE_IP}:27017/mongodb-user?authSource=admin"  